name: architecture
description: Student Tribe Flutter Application
publish_to: "none"

version: 3.3.9+72

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_inappwebview: ^6.1.0
  # Other dependencies as previously provided
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  easy_localization: ^3.0.7
  dio: ^5.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  localstore: ^1.4.0
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  change_app_package_name: ^1.3.0
  pin_code_fields: ^8.0.1
  rename_app: ^1.6.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  dotted_line: ^3.2.2
  get_it: ^8.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  simple_circular_progress_bar: ^1.0.2
  flutter_multi_formatter: ^2.13.0
  shared_preferences: ^2.3.0
  tuple: ^2.0.2
  share_plus: ^10.0.2
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  razorpay_flutter: ^1.3.7
  dotted_border: ^3.1.0
  qr_flutter: ^4.1.0
  logger: ^2.4.0
  flutter_widget_from_html: ^0.15.2
  easy_image_viewer: ^1.5.0
  custom_refresh_indicator: ^4.0.0
  firebase_core: ^3.6.0
  facebook_app_events: ^0.20.0
  firebase_crashlytics: ^4.1.1
  circular_progress_stack: ^0.0.3
  firebase_remote_config: ^5.2.0
  package_info_plus: ^8.0.2
  firebase_analytics: ^11.3.0
  flutter_linkify: ^6.0.0
  flutter_branch_sdk: ^7.0.3
  onesignal_flutter: ^5.3.4
  appcenter_sdk_flutter: ^0.5.1
  amplify_flutter: ^2.3.0
  amplify_auth_cognito: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/svg/
  generate: true

flutter_native_splash:
  color: "#CC202E"
  image: assets/images/logo_big.png
  android_12:
    color: "#CC202E"
    image: assets/images/logo_big.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#CC202E"
  adaptive_icon_foreground: "assets/images/android_launcher_icon.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false